swagger: '2.0'

info:
  version: "1.0.0"
  title: Lang71

schemes:
  - http
host: lang71.com
basePath: /api/v1
consumes:
   - application/json
produces:
  - application/json

################################################################################
#                                  Security                                    #
################################################################################
#securityDefinitions:
#  oauth:
#    type: oauth2
#    flow: implicit
#    authorizationUrl: http://lang71.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token
#    scopes:
#      basic: |
#       to read any and all data related to twitter
#security:
#  - oauth:
#    - basic


################################################################################
#                                           Paths                              #
################################################################################
paths:
  /login:
    post:
      description: |
        Create user session.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
          "200":
            description: OK
            schema:
              $ref: '#/definitions/Token'
          "401":
            description: Error
            schema:
              $ref: '#/definitions/Error'

  /register:
    put:
      description: |
        Create user profile.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Credentials'
      responses:
          "200":
            description: OK
            schema:
              $ref: '#/definitions/Token'
          "400":
            description: Error
            schema:
              $ref: '#/definitions/Error'


  /words/new:
    put:
      description: |
        Put new word to the server.
#      security:
#         - oauth:
#           - basic
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Word'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Word'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/Error'

  /words/{id}:
    delete:
      description: |
        Delete word.
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
          "200":
            description: OK
            schema:
             $ref: '#/definitions/Word'
          "400":
            description: Error
            schema:
              $ref: '#/definitions/Error'
    post:
      description: |
        Save statistic.
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: answer
          in: body
          schema:
            type: boolean
            title: answer
          required: true
      responses:
          "200":
            description: OK
          "400":
            description: Error
            schema:
              $ref: '#/definitions/Error'

  /words/all:
    get:
      description: |
        Get all user words.
      responses:
          "200":
            description: OK
            schema:
              title: ArrayOfWords
              type: array
              items:
                $ref: '#/definitions/Word'

          "400":
            description: Error
            schema:
              $ref: '#/definitions/Error'

  /words/random:
    get:
      description: |
        Get array of random words.
      parameters:
        - name: count
          in: body
          schema:
            type: integer
            title: count
          required: true
      responses:
          "200":
            description: OK
            schema:
              title: ArrayOfWords
              type: array
              items:
                $ref: '#/definitions/Word'

          "400":
            description: Error
            schema:
              $ref: '#/definitions/Error'
#            title: ArrayOfWords
#            type: array
#            items:
#              $ref: '#/definitions/Word'


################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  Error:
    type: object
    properties:
      message:
        type: string
  Credentials:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  Token:
    type: object
    properties:
      token:
        type: string
  Word:
    type: object
    properties:
      id:
        type: integer
      word:
        type: string
      meaning:
        type: string
